### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by noblejasper** [kevinsawicki/command-logger#7] opened 2015-01-21 01:59 UTC
I have 2 errors.

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/jasper/git/noblejasper/dotfiles/macosx/atom/packages/command-logger/lib/main.coffee:13:9)
```

```
Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
Object.activate - /Users/jasper/git/noblejasper/dotfiles/macosx/atom/packages/command-logger/lib/main.coffee:18:9
```

**Comment by kevinsawicki** [comment] 2015-01-21 02:24
Dupe of #6

**Closed by kevinsawicki** 2015-01-21 02:24 UTC
